# Generated by Django 4.0.5 on 2022-06-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='Timetable',
        ),
    ]
