# Generated by Django 4.0.5 on 2022-06-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_classroom_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance.subjectteacher'),
        ),
    ]
