# Generated by Django 4.0.5 on 2022-06-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='classroom',
        ),
        migrations.AddField(
            model_name='period',
            name='period',
            field=models.IntegerField(default=None),
        ),
    ]
