# Generated by Django 4.0.5 on 2022-06-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_period_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Period',
        ),
    ]
