# Generated by Django 4.0.5 on 2022-06-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_attendance_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance.subjectteacher'),
        ),
    ]
